# Bulk Loading
library(readxl)
library(tidyverse)
library(dplyr)
library(writexl)
library(fPortfolio)
library("timeSeries")
library("quantmod")
library("PerformanceAnalytics")
library("ggplot2")
library(zoo)
symbols=c("ICICIBANK.NS","ITC.NS","M&M.NS","GRASIM.NS","CIPLA.NS")
portfolio_stk <- lapply(symbols,function(X){
  getSymbols(X,from="2021-01-01",auto.assign = TRUE)
})
head(portfolio_stk)
class(portfolio_stk)
portfolio_stk_df <- as.data.frame(portfolio_stk)
class(portfolio_stk_df)
portfolio_stk_df <- Ad(portfolio_stk_df)
head(portfolio_stk_df)
portfolio_stk_df <- as.timeSeries(portfolio_stk_df)
portfolio_stk_ret <- Return.calculate(portfolio_stk_df)
head(portfolio_stk_ret)
portfolio_stk_ret <- na.omit(portfolio_stk_ret)
portfolio_stk_ret_pf <- Return.portfolio(portfolio_stk_ret,c(.2,.2,.2,.2,.2),geometric = FALSE)
efficientfrontier<-portfolioFrontier(ret,`setRiskFreeRate<-`(portfolioSpec(),.0640/252,constraints = "longOnly"))
min_var_portfolio <- minvariancePortfolio(portfolio_stk_ret,portfolioSpec(),constraints = "longOnly")
wts_min_var_port <- getWeights(min_var_portfolio)
Optimum_portfolio <- tangencyPortfolio(portfolio_stk_ret, `setRiskFreeRate<-`(portfolioSpec(),.0640/252),constraints="longOnly")
wts_optimum_portfolio <- getWeights(Optimum_portfolio)
wts_optimum_portfolio
efficient.frontier11 <- portfolioFrontier(portfolio_stk_ret,`setRiskFreeRate<-`(portfolioSpec(),.0640/252),constraints = "longonly")
plot(efficient.frontier11,c(1,2,3,4,5,8))


